platform :ios, '9.0'

target 'Todo' do
  use_frameworks!

  # Pods for Todo
pod 'RealmSwift'
pod 'SwipeCellKit'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'
end
